sylius_cms_admin_collection:
    resource: |
        alias: sylius_cms.collection
        section: admin
        templates: "@SyliusAdmin\\shared\\crud"
        redirect: update
        grid: sylius_cms_admin_collection
        form:
            type: Sylius\CmsPlugin\Form\Type\CollectionType
        except: ['show']
        permission: true
        vars:
            all:
                header: sylius_cms.ui.collections_header
                subheader: sylius_cms.ui.collections_subheader
                hook_prefix: 'sylius_cms.admin.collection'
    type: sylius.resource
