sylius_cms_admin_block:
    resource: "@SyliusCmsPlugin/config/routes/admin/block.yaml"

sylius_cms_admin_page:
    resource: "@SyliusCmsPlugin/config/routes/admin/page.yaml"

sylius_cms_admin_collection:
    resource: "@SyliusCmsPlugin/config/routes/admin/collection.yaml"

sylius_cms_admin_media:
    resource: "@SyliusCmsPlugin/config/routes/admin/media.yaml"

sylius_cms_admin_template:
    resource: "@SyliusCmsPlugin/config/routes/admin/template.yaml"
