sylius_twig_hooks:
    hooks:
        'sylius_cms.admin.page.create.content':
            form:
                component: 'sylius_cms:page:form'
                props:
                    resource: '@=_context.resource'
                    form: '@=_context.form'
                    template: '@SyliusCmsPlugin/admin/page/form.html.twig'
                priority: 0

        'sylius_cms.admin.page.create.content.form':
            sections:
                template: '@SyliusCmsPlugin/admin/page/form/sections.html.twig'
                priority: 0

        'sylius_cms.admin.page.create.content.form.sections':
            general:
                template: '@SyliusCmsPlugin/admin/page/form/sections/general.html.twig'
                priority: 300
            content:
                template: '@SyliusCmsPlugin/admin/page/form/sections/content.html.twig'
                priority: 200
            teaser:
                template: '@SyliusCmsPlugin/admin/page/form/sections/teaser.html.twig'
                priority: 100
            seo:
                template: '@SyliusCmsPlugin/admin/page/form/sections/seo.html.twig'
                priority: 0

        'sylius_cms.admin.page.create.content.form.sections.general':
            default:
                enabled: false
            name:
                template: '@SyliusCmsPlugin/admin/page/form/sections/general/name.html.twig'
                priority: 500
            code:
                template: '@SyliusCmsPlugin/admin/page/form/sections/general/code.html.twig'
                priority: 400
            enabled:
                template: '@SyliusCmsPlugin/admin/page/form/sections/general/enabled.html.twig'
                priority: 300
            channels:
                template: '@SyliusCmsPlugin/admin/page/form/sections/general/channels.html.twig'
                priority: 200
            collections:
                template: '@SyliusCmsPlugin/admin/page/form/sections/general/collections.html.twig'
                priority: 100
            publish_at:
                template: '@SyliusCmsPlugin/admin/page/form/sections/general/publish_at.html.twig'
                priority: 0

        'sylius_cms.admin.page.create.content.form.sections.content':
            locale:
                template: '@SyliusCmsPlugin/admin/page/form/sections/content/locale.html.twig'
                priority: 300
            template:
                template: '@SyliusCmsPlugin/admin/page/form/sections/content/template.html.twig'
                priority: 200
            elements_template:
                template: '@SyliusCmsPlugin/admin/page/form/sections/content/elements_template.html.twig'
                priority: 100
            elements:
                template: '@SyliusCmsPlugin/admin/page/form/sections/content/elements.html.twig'
                priority: 0

        'sylius_cms.admin.page.create.content.form.sections.teaser':
            translations:
                template: '@SyliusCmsPlugin/admin/page/form/sections/teaser/translations.html.twig'
                priority: 0

        'sylius_cms.admin.page.create.content.form.sections.teaser.translations':
            title:
                template: '@SyliusCmsPlugin/admin/page/form/sections/teaser/translations/title.html.twig'
                priority: 200
            content:
                template: '@SyliusCmsPlugin/admin/page/form/sections/teaser/translations/content.html.twig'
                priority: 100
            image:
                template: '@SyliusCmsPlugin/admin/page/form/sections/teaser/translations/image.html.twig'
                priority: 0

        'sylius_cms.admin.page.create.content.form.sections.seo':
            translations:
                template: '@SyliusCmsPlugin/admin/page/form/sections/seo/translations.html.twig'
                priority: 0

        'sylius_cms.admin.page.create.content.form.sections.seo.translations':
            meta_title:
                template: '@SyliusCmsPlugin/admin/page/form/sections/seo/translations/meta_title.html.twig'
                priority: 300
            slug:
                template: '@SyliusCmsPlugin/admin/page/form/sections/seo/translations/slug.html.twig'
                priority: 200
            meta_keywords:
                template: '@SyliusCmsPlugin/admin/page/form/sections/seo/translations/meta_keywords.html.twig'
                priority: 100
            meta_description:
                template: '@SyliusCmsPlugin/admin/page/form/sections/seo/translations/meta_description.html.twig'
                priority: 0
