sylius_twig_hooks:
    hooks:
        'sylius_cms.admin.template.update.content':
            form:
                component: 'sylius_cms:admin:template:form'
                props:
                    resource: '@=_context.resource'
                    form: '@=_context.form'
                    template: '@SyliusCmsPlugin/admin/template/form.html.twig'
                configuration:
                    method: 'PUT'
                priority: 0

        'sylius_cms.admin.template.update.content.form':
            sections:
                template: '@SyliusCmsPlugin/admin/template/form/sections.html.twig'
                priority: 0

        'sylius_cms.admin.template.update.content.form.sections':
            general:
                template: '@SyliusCmsPlugin/admin/template/form/sections/general.html.twig'
                priority: 0
            elements:
                template: '@SyliusCmsPlugin/admin/template/form/sections/elements.html.twig'
                priority: 0

        'sylius_cms.admin.template.update.content.form.sections.general':
            default:
                enabled: false
            name:
                template: '@SyliusCmsPlugin/admin/template/form/sections/general/name.html.twig'
                priority: 200
            type:
                template: '@SyliusCmsPlugin/admin/template/form/sections/general/type.html.twig'
                priority: 100

        'sylius_cms.admin.template.update.content.form.sections.elements':
            default:
                enabled: false
            content_elements:
                template: '@SyliusCmsPlugin/admin/template/form/sections/elements/content_elements.html.twig'
                priority: 0
