sylius_cms_admin_block:
    resource: "@SyliusCmsPlugin/config/routing/admin/block.yml"

sylius_cms_admin_page:
    resource: "@SyliusCmsPlugin/config/routing/admin/page.yml"

sylius_cms_admin_collection:
    resource: "@SyliusCmsPlugin/config/routing/admin/collection.yml"

sylius_cms_admin_media:
    resource: "@SyliusCmsPlugin/config/routing/admin/media.yml"

sylius_cms_admin_template:
    resource: "@SyliusCmsPlugin/config/routing/admin/template.yml"
