sylius_cms_shop_block:
    resource: "@SyliusCmsPlugin/config/routing/shop/block.yml"

sylius_cms_shop_page:
    resource: "@SyliusCmsPlugin/config/routing/shop/page.yml"

sylius_cms_shop_collection:
    resource: "@SyliusCmsPlugin/config/routing/shop/collection.yml"

sylius_cms_shop_media:
    resource: "@SyliusCmsPlugin/config/routing/shop/media.yml"
