sylius_twig_hooks:
    hooks:
        'sylius_cms.admin.collection.update.content':
            form:
                component: 'sylius_cms:collection:form'
                props:
                    resource: '@=_context.resource'
                    form: '@=_context.form'
                    template: '@SyliusCmsPlugin/admin/collection/form.html.twig'
                configuration:
                    method: 'PUT'
                priority: 0

        'sylius_cms.admin.collection.update.content.form':
            sections:
                template: '@SyliusCmsPlugin/admin/collection/form/sections.html.twig'
                priority: 0

        'sylius_cms.admin.collection.update.content.form.sections':
            general:
                template: '@SyliusCmsPlugin/admin/collection/form/sections/general.html.twig'
                priority: 100
            elements:
                template: '@SyliusCmsPlugin/admin/collection/form/sections/elements.html.twig'
                priority: 0

        'sylius_cms.admin.collection.update.content.form.sections.general':
            default:
                enabled: false
            code:
                template: '@SyliusCmsPlugin/admin/collection/form/sections/general/code.html.twig'
                priority: 300
            name:
                template: '@SyliusCmsPlugin/admin/collection/form/sections/general/name.html.twig'
                priority: 200
            type:
                template: '@SyliusCmsPlugin/admin/collection/form/sections/general/type.html.twig'
                priority: 100

        'sylius_cms.admin.collection.update.content.form.sections.elements':
            default:
                enabled: false
            collection_elements:
                template: '@SyliusCmsPlugin/admin/collection/form/sections/elements/collection_elements.html.twig'
                priority: 0
