imports:
    - { resource: "@SyliusCmsPlugin/config/grids.yaml" }
    - { resource: "@SyliusCmsPlugin/config/services.xml" }
    - { resource: "@SyliusCmsPlugin/config/fixtures/*.yaml"}
    - { resource: '@SyliusCmsPlugin/config/twig_hooks/**/*.yaml' }

parameters:
    sylius.sitemap.path: "%kernel.project_dir%/var/sitemap"
    sylius_cms_api_platform_mapping_path: '%kernel.project_dir%/vendor/sylius/cms-plugin/config/api_platform/'
    sylius_validation_group: [cms]
    sylius_cms.form.type.block.validation_groups: "%sylius_validation_group%"
    sylius_cms.form.type.content_configuration.validation_groups: "%sylius_validation_group%"
    sylius_cms.form.type.block_image.validation_groups: "%sylius_validation_group%"
    sylius_cms.form.type.page.validation_groups: "%sylius_validation_group%"
    sylius_cms.form.type.translation.page.validation_groups: "%sylius_validation_group%"
    sylius_cms.form.type.collection.validation_groups: "%sylius_validation_group%"
    sylius_cms.form.type.translation.media.validation_groups: "%sylius_validation_group%"
    sylius_cms.form.type.media.validation_groups: "%sylius_validation_group%"
    sylius_cms.form.type.template.validation_groups: "%sylius_validation_group%"
    sylius_cms.images_dir: "%sylius_core.images_dir%"
    sylius_cms.videos_dir: "%sylius_core.public_dir%/media/video"
    sylius_cms.files_dir: "%sylius_core.public_dir%/media/file"

api_platform:
    mapping:
        paths:
            - '%sylius_cms_api_platform_mapping_path%'

flysystem:
    storages:
        sylius_cms_media.image.storage:
            adapter: 'local'
            options:
                directory: '%sylius_cms.images_dir%'
            directory_visibility: 'public'
        sylius_cms_media.video.storage:
            adapter: 'local'
            options:
                directory: '%sylius_cms.videos_dir%'
            directory_visibility: 'public'
        sylius_cms_media.file.storage:
            adapter: 'local'
            options:
                directory: '%sylius_cms.files_dir%'
            directory_visibility: 'public'

sylius_ui:
    twig_ux:
        anonymous_component_template_prefixes:
            'sylius_cms:shop': "@SyliusCmsPlugin/shop/shared/components"

twig:
    form_themes:
        - '@SyliusCmsPlugin/admin/shared/editor/trix.html.twig'
