sylius_grid:
    grids:
        sylius_cms_admin_media:
            driver:
                name: doctrine/orm
                options:
                    class: "%sylius_cms.model.media.class%"
                    repository:
                        method: createListQueryBuilder
                        arguments: ["%locale%"]
            sorting:
                code: asc
            limits: [10, 25, 50]
            fields:
                media_file:
                    type: twig
                    label: sylius_cms.ui.preview
                    path: .
                    options:
                        template: "@SyliusCmsPlugin/admin/grid/field/image_preview.html.twig"
                name:
                    type: twig
                    label: sylius_cms.ui.name
                    sortable: name
                    options:
                        template: "@SyliusAdmin/shared/grid/field/name.html.twig"
                code:
                    type: twig
                    label: sylius_cms.ui.code
                    sortable: ~
                    options:
                        template: "@SyliusAdmin/shared/grid/field/code.html.twig"
                enabled:
                    type: twig
                    label: sylius.ui.enabled
                    options:
                        template: "@SyliusAdmin/shared/grid/field/boolean.html.twig"
                        vars:
                            th_class: "w-1 text-center"
                            td_class: "text-center"
                collections:
                    type: twig
                    label: sylius_cms.ui.collections
                    path: .
                    options:
                        template: "@SyliusCmsPlugin/admin/grid/field/collections.html.twig"
                channels:
                    type: twig
                    label: sylius_cms.ui.channels
                    options:
                        template: "@SyliusAdmin/shared/grid/field/channels.html.twig"
                        vars:
                            th_class: "w-1 text-center"
            filters:
                search:
                    type: string
                    label: sylius.ui.search
                    options:
                        fields: [code, translations.name]
                type:
                    type: select
                    label: sylius.ui.type
                    form_options:
                        choices:
                            sylius.ui.image: !php/const Sylius\CmsPlugin\Entity\MediaInterface::IMAGE_TYPE
                            sylius_cms.ui.file: !php/const Sylius\CmsPlugin\Entity\MediaInterface::FILE_TYPE
                            sylius_cms.ui.video: !php/const Sylius\CmsPlugin\Entity\MediaInterface::VIDEO_TYPE
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
                bulk:
                    delete:
                        type: delete
