sylius_twig_hooks:
    hooks:
        'sylius_cms.admin.block.update.content':
            form:
                component: 'sylius_cms:admin:block:form'
                props:
                    resource: '@=_context.resource'
                    form: '@=_context.form'
                    template: '@SyliusCmsPlugin/admin/block/form.html.twig'
                configuration:
                    method: 'PUT'
                priority: 0

        'sylius_cms.admin.block.update.content.form':
            sections:
                template: '@SyliusCmsPlugin/admin/block/form/sections.html.twig'
                priority: 0

        'sylius_cms.admin.block.update.content.form.sections':
            general:
                template: '@SyliusCmsPlugin/admin/block/form/sections/general.html.twig'
                priority: 300
            collections:
                template: '@SyliusCmsPlugin/admin/block/form/sections/collections.html.twig'
                priority: 200
            display_config:
                template: '@SyliusCmsPlugin/admin/block/form/sections/display_config.html.twig'
                priority: 100
            content:
                template: '@SyliusCmsPlugin/admin/block/form/sections/content.html.twig'
                priority: 0

        'sylius_cms.admin.block.update.content.form.sections.general':
            default:
                enabled: false
            code:
                template: '@SyliusCmsPlugin/admin/block/form/sections/general/code.html.twig'
                priority: 300
            name:
                template: '@SyliusCmsPlugin/admin/block/form/sections/general/name.html.twig'
                priority: 200
            enabled:
                template: '@SyliusCmsPlugin/admin/block/form/sections/general/enabled.html.twig'
                priority: 100
            channels:
                template: '@SyliusCmsPlugin/admin/block/form/sections/general/channels.html.twig'
                priority: 0

        'sylius_cms.admin.block.update.content.form.sections.display_config':
            default:
                enabled: false
            products:
                template: '@SyliusCmsPlugin/admin/block/form/sections/display_config/products.html.twig'
                priority: 200
            productsInTaxons:
                template: '@SyliusCmsPlugin/admin/block/form/sections/display_config/products_in_taxons.html.twig'
                priority: 100
            taxons:
                template: '@SyliusCmsPlugin/admin/block/form/sections/display_config/taxons.html.twig'
                priority: 0

        'sylius_cms.admin.block.update.content.form.sections.content':
            template:
                template: '@SyliusCmsPlugin/admin/block/form/sections/content/template.html.twig'
                priority: 100
            translations:
                template: '@SyliusCmsPlugin/admin/block/form/sections/content/translations.html.twig'
                priority: 0

        'sylius_cms.admin.block.update.content.form.sections.content.translations':
            elements_template:
                template: '@SyliusCmsPlugin/admin/block/form/sections/content/translations/elements_template.html.twig'
                priority: 100
            elements:
                template: '@SyliusCmsPlugin/admin/block/form/sections/content/translations/elements.html.twig'
                priority: 0
