sylius_cms_admin_template:
    resource: |
        alias: sylius_cms.template
        section: admin
        templates: "@SyliusAdmin\\shared\\crud"
        except: ['show']
        redirect: update
        grid: sylius_cms_admin_template
        form:
            type: Sylius\CmsPlugin\Form\Type\TemplateType
        permission: true
        vars:
            all:
                hook_prefix: 'sylius_cms.admin.template'
    type: sylius.resource
